<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-06 16:13

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('ig_ldap_sso_auth');
$autoload = array(
	'tx_igldapssoauth_task_importusers' => $extensionPath . 'Classes/Task/ImportUsers.php',
	'tx_igldapssoauth_task_importusersadditionalfields' => $extensionPath . 'Classes/Task/ImportUsersAdditionalFields.php',
	'tx_igldapssoauth_domain_repository_configurationrepository' => $extensionPath . 'Classes/Domain/Repository/ConfigurationRepository.php',
	'tx_igldapssoauth_auth'				=>	$extensionPath . 'Classes/Library/Auth.php',
	'tx_igldapssoauth_config'			=>	$extensionPath . 'Classes/Library/Config.php',
	'tx_igldapssoauth_ldap_group'		=>	$extensionPath . 'Classes/Library/LdapGroup.php',
	'tx_igldapssoauth_ldap_user'		=>	$extensionPath . 'Classes/Library/LdapUser.php',
	'tx_igldapssoauth_ldap'				=>	$extensionPath . 'Classes/Library/Ldap.php',
	'tx_igldapssoauth_tca_form_suggest'	=>	$extensionPath . 'Classes/Tca/Form/Suggest.php',
	'tx_igldapssoauth_typo3_group'		=>	$extensionPath . 'Classes/Library/Typo3Group.php',
	'tx_igldapssoauth_typo3_user'		=>	$extensionPath . 'Classes/Library/Typo3User.php',
	'tx_igldapssoauth_utility_debug'	=>	$extensionPath . 'Classes/Utility/Debug.php',
	'tx_igldapssoauth_utility_ldap'		=>	$extensionPath . 'Classes/Utility/Ldap.php',
	'tx_igldapssoauth_utility_notification' => $extensionPath . 'Classes/Utility/Notification.php',
	'tx_igldapssoauth_utility_userimport' => $extensionPath . 'Classes/Utility/UserImport.php',
	'tx_igldapssoauth_sv1'				=>	$extensionPath . 'Classes/Service/Sv1.php',
);

return $autoload;
