<?php
return [
    'tx_igldapssoauth_auth' => 'Causal\\IgLdapSsoAuth\\Library\\Authentication',
    'tx_igldapssoauth_config' => 'Causal\\IgLdapSsoAuth\\Library\\Configuration',
    'tx_igldapssoauth_emconfhelper' => 'Causal\\IgLdapSsoAuth\\Em\\ConfigurationHelper',
    'tx_igldapssoauth_ldap' => 'Causal\\IgLdapSsoAuth\\Library\\Ldap',
    'tx_igldapssoauth_ldap_group' => 'Causal\\IgLdapSsoAuth\\Library\\LdapGroup',
    'tx_igldapssoauth_sv1' => 'Causal\\IgLdapSsoAuth\\Service\\AuthenticationService',
    'tx_igldapssoauth_typo3_group' => 'Causal\\IgLdapSsoAuth\\Domain\\Repository\\Typo3GroupRepository',
    'tx_igldapssoauth_typo3_user' => 'Causal\\IgLdapSsoAuth\\Domain\\Repository\\Typo3UserRepository',
    'tx_igldapssoauth_utility_Ldap' => 'Causal\\IgLdapSsoAuth\\Utility\\LdapUtility',
    'Tx_IgLdapSsoAuth_Domain_Repository_ConfigurationRepository' => 'Causal\\IgLdapSsoAuth\\Domain\\Repository\\ConfigurationRepository',
    'Tx_IgLdapSsoAuth_Hooks_DataHandler' => 'Causal\\IgLdapSsoAuth\\Hooks\\DataHandler',
    'Tx_IgLdapSsoAuth_Hooks_DatabaseRecordListIconUtility' => 'Causal\\IgLdapSsoAuth\\Hooks\\DatabaseRecordListIconUtility',
    'Tx_IgLdapSsoAuth_Hooks_SetupModuleController' => 'Causal\\IgLdapSsoAuth\\Hooks\\SetupModuleController',
    'Tx_IgLdapSsoAuth_Task_ImportUsers' => 'Causal\\IgLdapSsoAuth\\Task\\ImportUsers',
    'Tx_IgLdapSsoAuth_Task_ImportUsersAdditionalFields' => 'Causal\\IgLdapSsoAuth\\Task\\ImportUsersAdditionalFields',
    'Tx_IgLdapSsoAuth_Tca_Form_Suggest' => 'Causal\\IgLdapSsoAuth\\Tca\\Form\\SuggestWizard',
    'Tx_IgLdapSsoAuth_Utility_Debug' => 'Causal\\IgLdapSsoAuth\\Utility\\DebugUtility',
    'Tx_IgLdapSsoAuth_Utility_ExtraDataProcessorInterface' => 'Causal\\IgLdapSsoAuth\\Utility\\ExtraDataProcessorInterface',
    'Tx_IgLdapSsoAuth_Utility_Notification' => 'Causal\\IgLdapSsoAuth\\Utility\\NotificationUtility',
    'Tx_IgLdapSsoAuth_Utility_UserImport' => 'Causal\\IgLdapSsoAuth\\Utility\\UserImportUtility',
];
