services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Causal\IgLdapSsoAuth\:
    resource: '../Classes/*'

  Causal\IgLdapSsoAuth\Domain\Repository\ConfigurationRepository:
    public: true

  Causal\IgLdapSsoAuth\Library\Ldap:
    public: true

  Causal\IgLdapSsoAuth\Utility\LdapUtility:
    public: true

  Causal\IgLdapSsoAuth\Utility\NotificationUtility:
    public: true

  # Register type converter
  Causal\IgLdapSsoAuth\Property\TypeConverter\ConfigurationConverter:
    tags:
      - name: extbase.type_converter
        priority: 10
        target: Causal\IgLdapSsoAuth\Domain\Model\Configuration
        sources: int,string

  # Register event listeners
  Causal\IgLdapSsoAuth\EventListener\ExtendUserGroupQueryListener:
    tags:
      - name: event.listener
        identifier: 'causal.ig_ldap_sso_auth.extendUserGroupQueryListener'
        event: TYPO3\CMS\Backend\View\Event\ModifyDatabaseQueryForRecordListingEvent

  Causal\IgLdapSsoAuth\EventListener\OverrideIconOverlayListener:
    tags:
      - name: event.listener
        identifier: 'causal.ig_ldap_sso_auth.overrideIconOverlayListener'
        event: TYPO3\CMS\Core\Imaging\Event\ModifyRecordOverlayIconIdentifierEvent

  # Register command
  Causal\IgLdapSsoAuth\Command\ImportUsers:
    tags:
      - name: console.command
        command: 'ldap:importusers'
        description: 'Import users for a given LDAP configuration'
